<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-L7E7ROD" failures="1" tests="5" name="batch.User_TC" time="240.678" errors="0" timestamp="2023-03-29T10:32:44 IST" skipped="3">
  <testcase classname="batch.User_TC" name="wishList" time="51.597">
    <skipped/>
  </testcase> <!-- wishList -->
  <system-out>
    <![CDATA[wishList=======> test script execution started]]>
  </system-out>
  <testcase classname="batch.User_TC" name="wishList" time="41.449">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at batch.User_TC.wishList(User_TC.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- wishList -->
  <system-out>
    <![CDATA[wishList=======> test script execution started]]>
  </system-out>
  <testcase classname="batch.User_TC" name="wishList" time="44.895">
    <skipped/>
  </testcase> <!-- wishList -->
  <system-out>
    <![CDATA[wishList=======> test script execution started]]>
  </system-out>
  <testcase classname="batch.User_TC" name="wishList" time="38.731">
    <skipped/>
  </testcase> <!-- wishList -->
  <system-out>
    <![CDATA[wishList=======> test script execution started]]>
  </system-out>
  <testcase classname="batch.User_TC" name="wishListToAddToCart" time="64.006"/>
  <system-out>
    <![CDATA[wishListToAddToCart=======> test script execution started]]>
  </system-out>
</testsuite> <!-- batch.User_TC -->
